# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
