# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 04:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170819_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='slug',
        ),
    ]
