# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-19 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_evento_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(),
        ),
    ]
