# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-14 14:54
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('apresentacao', models.TextField()),
                ('foto', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='foto')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
